name: The ForSyDe-LaTeX Utilities
description: TikZ/PGF libraries for ForSyDe documents
theme: jekyll-theme-slate

show_downloads: true

parent-url: https://forsyde.github.io

maintainer:
  name: ugeorge
  url: https://github.com/ugeorge

github:
  zip_url: https://github.com/forsyde/forsyde-latex/archive/master.zip
  tar_url: https://github.com/forsyde/forsyde-latex/archive/master.tar.gz

## google analytics
google_analytics: UA-113668562-1

## paths to exclude from the site generation
exclude: [script, Gemfile, Gemfile.lock, jekyll-theme-slate.gemspec]